version: "3.8"
services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./api/src/db/migration.sql:/docker-entrypoint-initdb.d/migration.sql
      - ./api/src/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
  api:
    image: hacking-transitions-19/api
    container_name: api-1
    restart: always
    build: ./api
    environment:
      DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@database/${{ secrets.POSTGRES_DB }}
      NODE_ENV: development
      PORT: 80
    depends_on:
      - database
    ports:
      - ${{ secrets.API_PORT }}:80
    volumes:
      - ./api/src:/code/src
    command: npm run dev
  app:
    image: hacking-transitions-19/web
    container_name: app-1
    restart: always
    build: ./client
    environment:
      API_URL: http://api
      PORT: ${{ secrets.CLIENT_PORT }}
    depends_on:
      - api
    ports:
      - ${{ secrets.CLIENT_PORT }}:${{ secrets.CLIENT_PORT }}
    volumes:
      - ./client/src:/code/src
    command: npm run dev
volumes:
  pg-data:
