version: "3.8"
services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./api/src/db/migration.sql:/docker-entrypoint-initdb.d/migration.sql
      - ./api/src/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
  api:
    image: hacking-transitions-19/api
    container_name: api-1
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}
      NODE_ENV: development
      PORT: 80
    depends_on:
      - database
    ports:
      - ${API_PORT}:80
    volumes:
      - ./api/src:/code/src
    command: npm run dev
  app:
    image: hacking-transitions-19/web
    container_name: app-1
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      API_URL: http://api
      PORT: ${CLIENT_PORT}
    depends_on:
      - api
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/src:/code/src
    command: npm run dev
volumes:
  pg-data:


