name: e2e testing

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker images
        run: docker-compose -f docker-compose.test.yml build
      - name: Start Docker Compose
        run: docker-compose -f docker-compose.test.yml up -d
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with: 
          start: wait-on http://localhost:${{ secrets.CLIENT_PORT }} && npm run cypress:run
      - name: Stop Docker Compose
        run: docker-compose -f docker-compose.test.yml down
