name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      API_PORT: ${{ secrets.API_PORT }}
      CLIENT_PORT: ${{ secrets.CLIENT_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and tag Docker images
        run: |
          docker build -t my-app-db:latest ./database
          docker build -t my-app-api:latest ./api
          docker build -t my-app-web:latest ./client

      - name: Start Docker Compose
        run: |
          docker-compose up -d

      - name: Wait for services to start
        run: sleep 10

      - name: Run end-to-end tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run cy:run
          wait-on: 'http://localhost:${{ secrets.CLIENT_PORT }}'
        env:
          CYPRESS_baseUrl: http://localhost:${{ secrets.CLIENT_PORT }}
          CYPRESS_databaseUrl: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:${{ secrets.POSTGRES_PORT }}/${{ secrets.POSTGRES_DB }}